# Generated by Django 4.2.4 on 2023-08-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_card_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
