# Generated by Django 4.2.4 on 2023-09-06 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='name',
        ),
    ]
