# Generated by Django 4.2.5 on 2023-09-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_rename_first_name_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='link',
        ),
        migrations.AddField(
            model_name='card',
            name='link_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
