# Generated by Django 4.2.5 on 2023-09-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_remove_card_link_card_link_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='link_name',
            new_name='link',
        ),
    ]
